### ISSUE TITLE
unable to install in python2.7

### ISSUE THREAD

**Issue by cslxiao** [TobyPDE/chianti#2]
running install
running build
running build_ext
building 'chianti' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c dataprovider.cpp -o build/temp.linux-x86_64-2.7/dataprovider.o -std=c++11 -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1777:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from dataprovider.cpp:2:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from dataprovider.cpp:5:0:
utils.h: In static member function ‘static std::string PythonUtils::objectToString(PyObject*)’:
utils.h:121:61: error: ‘PyUnicode_AsUTF8AndSize’ was not declared in this scope
         return std::string(PyUnicode_AsUTF8AndSize(object, 0));
                                                             ^
dataprovider.cpp: At global scope:
dataprovider.cpp:30:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
 };
 ^
dataprovider.cpp:30:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
dataprovider.cpp:30:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
dataprovider.cpp:30:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
dataprovider.cpp: In function ‘int PyDataProvider_init(PyDataProvider*, PyObject*, PyObject*)’:
dataprovider.cpp:280:75: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     static char *keywordList[] = {"iterator", "batchsize", "augmentors", 0};
                                                                           ^
dataprovider.cpp:280:75: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
dataprovider.cpp:280:75: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
dataprovider.cpp: In function ‘PyObject* sequentialIterator(PyObject*, PyObject*, PyObject*)’:
dataprovider.cpp:447:45: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     static char *keywordList[] = {"files", 0};
                                             ^
dataprovider.cpp: In function ‘PyObject* randomIterator(PyObject*, PyObject*, PyObject*)’:
dataprovider.cpp:485:45: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     static char *keywordList[] = {"files", 0};
                                             ^
dataprovider.cpp: In function ‘PyObject* sampleIterator(PyObject*, PyObject*, PyObject*)’:
dataprovider.cpp:523:56: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     static char *keywordList[] = {"files", "weights", 0};
                                                        ^
dataprovider.cpp:523:56: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
dataprovider.cpp: In function ‘PyObject* subsampleAugmentor(PyObject*, PyObject*, PyObject*)’:
dataprovider.cpp:568:46: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     static char *keywordList[] = {"factor", 0};
                                              ^
dataprovider.cpp: In function ‘PyObject* gammaAugmentor(PyObject*, PyObject*, PyObject*)’:
dataprovider.cpp:590:45: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     static char *keywordList[] = {"gamma", 0};
                                             ^
dataprovider.cpp: In function ‘PyObject* translationAugmentor(PyObject*, PyObject*, PyObject*)’:
dataprovider.cpp:612:46: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     static char *keywordList[] = {"offset", 0};
                                              ^
dataprovider.cpp: In function ‘PyObject* zoomingAugmentor(PyObject*, PyObject*, PyObject*)’:
dataprovider.cpp:634:45: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
     static char *keywordList[] = {"range", 0};
                                             ^
dataprovider.cpp: At global scope:
dataprovider.cpp:679:27: error: variable ‘PyModuleDef chiantiModule’ has initializer but incomplete type
 static struct PyModuleDef chiantiModule = {
                           ^
dataprovider.cpp:680:9: error: ‘PyModuleDef_HEAD_INIT’ was not declared in this scope
         PyModuleDef_HEAD_INIT,
         ^
In file included from /usr/include/c++/4.8/cstddef:42:0,
                 from /usr/local/include/opencv2/core/core.hpp:58,
                 from /usr/local/include/opencv2/opencv.hpp:47,
                 from chianti/common.h:3,
                 from chianti/provider.h:3,
                 from dataprovider.cpp:4:
dataprovider.cpp: In function ‘void PyInit_chianti()’:
dataprovider.cpp:699:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:701:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:703:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:705:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:707:39: error: ‘PyModule_Create’ was not declared in this scope
     m = PyModule_Create(&chiantiModule);
                                       ^
In file included from /usr/include/c++/4.8/cstddef:42:0,
                 from /usr/local/include/opencv2/core/core.hpp:58,
                 from /usr/local/include/opencv2/opencv.hpp:47,
                 from chianti/common.h:3,
                 from chianti/provider.h:3,
                 from dataprovider.cpp:4:
dataprovider.cpp:709:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:723:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
     return m;
            ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by TobyPDE** [comment]
You're compiling against the Python 2.7 API. Please use the Python 3.5 API in order to build the module.
