### ISSUE TITLE
The problems of install chiati. How can I solve this problem?

### ISSUE THREAD

**Issue by Youngkl0726** [TobyPDE/chianti#3]
$ python setup.py install
running install
running build
running build_ext
building 'chianti' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/mnt/lustre/yangkunlin/pyuser/testpy/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c dataprovider.cpp -o build/temp.linux-x86_64-2.7/dataprovider.o -std=c++11 -fopenmp
In file included from dataprovider.cpp:7:0:
utils.h: In static member function ‘static std::string PythonUtils::objectToString(PyObject*)’:
utils.h:121:61: error: ‘PyUnicode_AsUTF8AndSize’ was not declared in this scope
         return std::string(PyUnicode_AsUTF8AndSize(object, 0));
                                                             ^
dataprovider.cpp: At global scope:
dataprovider.cpp:804:27: error: variable ‘PyModuleDef chiantiModule’ has initializer but incomplete type
 static struct PyModuleDef chiantiModule = {
                           ^
dataprovider.cpp:805:9: error: ‘PyModuleDef_HEAD_INIT’ was not declared in this scope
         PyModuleDef_HEAD_INIT,
         ^
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from /usr/include/opencv2/core/core.hpp:58,
                 from /usr/include/opencv2/opencv.hpp:47,
                 from chianti/common.h:3,
                 from chianti/provider.h:3,
                 from dataprovider.cpp:6:
dataprovider.cpp: In function ‘void PyInit_chianti()’:
dataprovider.cpp:824:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:826:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:828:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:830:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:832:39: error: ‘PyModule_Create’ was not declared in this scope
     m = PyModule_Create(&chiantiModule);
                                       ^
In file included from /usr/include/c++/4.8.2/cstddef:42:0,
                 from /usr/include/opencv2/core/core.hpp:58,
                 from /usr/include/opencv2/opencv.hpp:47,
                 from chianti/common.h:3,
                 from chianti/provider.h:3,
                 from dataprovider.cpp:6:
dataprovider.cpp:834:16: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return NULL;
                ^
dataprovider.cpp:848:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
     return m;
            ^
error: command 'gcc' failed with exit status 1

**Comment by TobyPDE** [comment]
I rewrote the library and the main FRRN code. You no longer need Chianti if you don't care too much about performance. The problem you encountered was because you used Python 2.7 instead of 3.5.
